services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./yuhu:/code
    depends_on:
      - database
      - rabbitmq
      - celery_worker
    env_file:
      - .env
  database:
    image: postgres:16.2
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A yuhu worker --loglevel=info
    depends_on:
      - rabbitmq
    volumes:
      - ./yuhu:/code
    env_file:
      - .env
  jupyter-notebook:
    image: jupyter/minimal-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./yuhu:/home/jovyan
    env_file:
      - .env

volumes:
  postgres_data:
  rabbitmq_data: {}
