services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./yuhu:/code
    depends_on:
      - rabbitmq
      #- celery_worker
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A yuhu worker --loglevel=info
    depends_on:
      - rabbitmq
    volumes:
      - ./yuhu:/code
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: celery -A yuhu beat --loglevel=info
    depends_on:
      - rabbitmq
    volumes:
      - ./yuhu:/code
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq
  jupyter-notebook:
    image: jupyter/minimal-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./yuhu:/home/jovyan
    environment:
      - JUPYTER_TOKEN=mi_token_secreto

volumes:
  rabbitmq_data: {}
